// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The representation of a key managed by the API Keys API.
public struct Key: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the key.
  /// The `name` has the form:
  /// `projects/<PROJECT_NUMBER>/locations/global/keys/<KEY_ID>`.
  /// For example:
  /// `projects/123456867718/locations/global/keys/b7ff1f9f-8275-410a-94dd-3855ee9b5dd2`
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  public var name: Swift.String = Swift.String()

  /// Output only. Unique id in UUID4 format.
  public var uid: Swift.String = Swift.String()

  /// Human-readable display name of this key that you can modify.
  /// The maximum length is 63 characters.
  public var displayName: Swift.String = Swift.String()

  /// Output only. An encrypted and signed value held by this key.
  /// This field can be accessed only through the `GetKeyString` method.
  public var keyString: Swift.String = Swift.String()

  /// Output only. A timestamp identifying the time this key was originally
  /// created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. A timestamp identifying the time this key was last
  /// updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. A timestamp when this key was deleted. If the resource is not
  /// deleted, this must be empty.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Annotations is an unstructured key-value map stored with a policy that
  /// may be set by external tools to store and retrieve arbitrary metadata.
  /// They are not queryable and should be preserved when modifying objects.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Key restrictions.
  public var restrictions: Restrictions? = nil

  /// Output only. A checksum computed by the server based on the current value
  /// of the Key resource. This may be sent on update and delete requests to
  /// ensure the client has an up-to-date value before proceeding. See
  /// https://google.aip.dev/154.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Key`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Key().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.apikeys.v2.Key"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
