// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Manages the API keys associated with projects.
///
/// @Snippet(path: "ApiKeysQuickstart")
public class ApiKeysClient: Clients.ApiKeysProtocol {
  let inner: any Clients.ApiKeysStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ApiKeysClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiKeysStub = try Clients.ApiKeysTransport(options)
    inner = Clients.ApiKeysRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiKeysLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_CreateKey")
  public func createKey(
    request: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createKey(request: request, options: options)
  }

  /// Creates a new API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_CreateKey")
  public func createKey(
    withPolling: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Key>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Key(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the API keys owned by a project. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_ListKeys")
  public func listKeys(
    request: ListKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.ListKeysResponse {
    try await self.inner.listKeys(request: request, options: options)
  }

  /// Lists the API keys owned by a project. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_ListKeys")
  public func listKeys(
    byItem: ListKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Key, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleApiApiKeysV1.ListKeysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listKeys(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the metadata for an API key. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_GetKey")
  public func getKey(
    request: GetKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.Key {
    try await self.inner.getKey(request: request, options: options)
  }

  /// Get the key string for an API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_GetKeyString")
  public func getKeyString(
    request: GetKeyStringRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    try await self.inner.getKeyString(request: request, options: options)
  }

  /// Patches the modifiable fields of an API key.
  /// The key string of the API key isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UpdateKey")
  public func updateKey(
    request: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateKey(request: request, options: options)
  }

  /// Patches the modifiable fields of an API key.
  /// The key string of the API key isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UpdateKey")
  public func updateKey(
    withPolling: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Key>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Key(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an API key. Deleted key can be retrieved within 30 days of
  /// deletion. Afterward, key will be purged from the project.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_DeleteKey")
  public func deleteKey(
    request: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteKey(request: request, options: options)
  }

  /// Deletes an API key. Deleted key can be retrieved within 30 days of
  /// deletion. Afterward, key will be purged from the project.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_DeleteKey")
  public func deleteKey(
    withPolling: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Key>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Key(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeletes an API key which was deleted within 30 days.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UndeleteKey")
  public func undeleteKey(
    request: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeleteKey(request: request, options: options)
  }

  /// Undeletes an API key which was deleted within 30 days.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UndeleteKey")
  public func undeleteKey(
    withPolling: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Key>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Key(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.undeleteKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Find the parent project and resource name of the API
  /// key that matches the key string in the request. If the API key has been
  /// purged, resource name will not be set.
  /// The service account must have the `apikeys.keys.lookup` permission
  /// on the parent project.
  ///
  /// @Snippet(path: "ApiKeys_LookupKey")
  public func lookupKey(
    request: LookupKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse {
    try await self.inner.lookupKey(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiKeys_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiKeysClient`.
  ///
  /// To mock `ApiKeysClient` change your functions to receive
  /// `some ApiKeysProtocol` or `any ApiKeysProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiKeysProtocol {
    /// See `ApiKeysClient.createKey`.
    func createKey(request: CreateKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.createKey`.
    func createKey(withPolling: CreateKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Key>

    /// See `ApiKeysClient.createKey`.
    func createKey(
      parent: Swift.String,
      key: Key?,
      keyId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.listKeys`.
    func listKeys(request: ListKeysRequest) async throws -> GoogleApiApiKeysV1.ListKeysResponse

    /// See `ApiKeysClient.listKeys`.
    func listKeys(
      byItem: ListKeysRequest
    ) throws -> any AsyncSequence<Key, Swift.Error>

    /// See `ApiKeysClient.listKeys`.
    func listKeys(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Key, Swift.Error>

    /// See `ApiKeysClient.getKey`.
    func getKey(request: GetKeyRequest) async throws -> GoogleApiApiKeysV1.Key

    /// See `ApiKeysClient.getKey`.
    func getKey(
      name: Swift.String,
    ) async throws -> GoogleApiApiKeysV1.Key

    /// See `ApiKeysClient.getKeyString`.
    func getKeyString(request: GetKeyStringRequest) async throws
      -> GoogleApiApiKeysV1.GetKeyStringResponse

    /// See `ApiKeysClient.getKeyString`.
    func getKeyString(
      name: Swift.String,
    ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse

    /// See `ApiKeysClient.updateKey`.
    func updateKey(request: UpdateKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.updateKey`.
    func updateKey(withPolling: UpdateKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Key>

    /// See `ApiKeysClient.updateKey`.
    func updateKey(
      key: Key?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(request: DeleteKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(withPolling: DeleteKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Key>

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKey(request: UndeleteKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKey(withPolling: UndeleteKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Key>

    /// See `ApiKeysClient.lookupKey`.
    func lookupKey(request: LookupKeyRequest) async throws -> GoogleApiApiKeysV1.LookupKeyResponse

    /// See `ApiKeysClient.createKey`.
    func createKey(
      request: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.createKey`.
    func createKey(
      withPolling: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.listKeys`.
    func listKeys(
      request: ListKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.ListKeysResponse

    /// See `ApiKeysClient.listKeys`.
    func listKeys(
      byItem: ListKeysRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Key, Swift.Error>

    /// See `ApiKeysClient.getKey`.
    func getKey(
      request: GetKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.Key

    /// See `ApiKeysClient.getKeyString`.
    func getKeyString(
      request: GetKeyStringRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse

    /// See `ApiKeysClient.updateKey`.
    func updateKey(
      request: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.updateKey`.
    func updateKey(
      withPolling: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(
      request: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(
      withPolling: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKey(
      request: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKey(
      withPolling: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Key>

    /// See `ApiKeysClient.lookupKey`.
    func lookupKey(
      request: LookupKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse
  }
}

// Default implementations
extension Clients.ApiKeysProtocol {
  public func createKey(request: CreateKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createKey(request: request, options: .init())
  }

  public func createKey(
    request: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createKey(withPolling: CreateKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Key>
  {
    try await self.createKey(withPolling: withPolling, options: .init())
  }

  public func createKey(
    withPolling: CreateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createKey(
    parent: Swift.String,
    key: Key?,
    keyId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let request = CreateKeyRequest().with {
      $0.parent = parent
      $0.key = key
      $0.keyId = keyId
    }
    return try await self.createKey(withPolling: request)
  }

  public func listKeys(request: ListKeysRequest) async throws -> GoogleApiApiKeysV1.ListKeysResponse
  {
    try await self.listKeys(request: request, options: .init())
  }

  public func listKeys(
    request: ListKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.ListKeysResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listKeys(
    byItem: ListKeysRequest
  ) throws -> any AsyncSequence<Key, Swift.Error> {
    try self.listKeys(byItem: byItem, options: .init())
  }

  public func listKeys(
    byItem: ListKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Key, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleApiApiKeysV1.ListKeysResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listKeys(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Key, Swift.Error> {
    let request = ListKeysRequest().with {
      $0.parent = parent
    }
    return try self.listKeys(byItem: request)
  }

  public func getKey(request: GetKeyRequest) async throws -> GoogleApiApiKeysV1.Key {
    try await self.getKey(request: request, options: .init())
  }

  public func getKey(
    request: GetKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.Key {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getKey(
    name: Swift.String,
  ) async throws -> GoogleApiApiKeysV1.Key {
    let request = GetKeyRequest().with {
      $0.name = name
    }
    return try await self.getKey(request: request)
  }

  public func getKeyString(request: GetKeyStringRequest) async throws
    -> GoogleApiApiKeysV1.GetKeyStringResponse
  {
    try await self.getKeyString(request: request, options: .init())
  }

  public func getKeyString(
    request: GetKeyStringRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getKeyString(
    name: Swift.String,
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    let request = GetKeyStringRequest().with {
      $0.name = name
    }
    return try await self.getKeyString(request: request)
  }

  public func updateKey(request: UpdateKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateKey(request: request, options: .init())
  }

  public func updateKey(
    request: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateKey(withPolling: UpdateKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Key>
  {
    try await self.updateKey(withPolling: withPolling, options: .init())
  }

  public func updateKey(
    withPolling: UpdateKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateKey(
    key: Key?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let request = UpdateKeyRequest().with {
      $0.key = key
      $0.updateMask = updateMask
    }
    return try await self.updateKey(withPolling: request)
  }

  public func deleteKey(request: DeleteKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteKey(request: request, options: .init())
  }

  public func deleteKey(
    request: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteKey(withPolling: DeleteKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Key>
  {
    try await self.deleteKey(withPolling: withPolling, options: .init())
  }

  public func deleteKey(
    withPolling: DeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteKey(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let request = DeleteKeyRequest().with {
      $0.name = name
    }
    return try await self.deleteKey(withPolling: request)
  }

  public func undeleteKey(request: UndeleteKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.undeleteKey(request: request, options: .init())
  }

  public func undeleteKey(
    request: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func undeleteKey(withPolling: UndeleteKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Key>
  {
    try await self.undeleteKey(withPolling: withPolling, options: .init())
  }

  public func undeleteKey(
    withPolling: UndeleteKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Key>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func lookupKey(request: LookupKeyRequest) async throws
    -> GoogleApiApiKeysV1.LookupKeyResponse
  {
    try await self.lookupKey(request: request, options: .init())
  }

  public func lookupKey(
    request: LookupKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
