// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ApiKeysStub: Sendable {
    func createKey(
      request: CreateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listKeys(
      request: ListKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.ListKeysResponse

    func getKey(
      request: GetKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.Key

    func getKeyString(
      request: GetKeyStringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse

    func updateKey(
      request: UpdateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteKey(
      request: DeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeleteKey(
      request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func lookupKey(
      request: LookupKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
