// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages the API keys associated with projects.
///
/// @Snippet(path: "ApiKeysQuickstart")
public final class ApiKeysClient: Clients.ApiKeysProtocol, Sendable {
  let inner: any Clients.ApiKeysStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `ApiKeysClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiKeysStub = try Clients.ApiKeysTransport(options)
    inner = Clients.ApiKeysRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiKeysLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_CreateKey")
  public func createKey(
    request: CreateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createKey(request: request, options: options)
  }

  /// Creates a new API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_CreateKey")
  public func createKeyPollingUntilDone(
    request: CreateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Key>.State in
      return try op._extractStatus(Key.self)
    }
    let rawOp = try await self.createKey(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the API keys owned by a project. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_ListKeys")
  public func listKeys(
    request: ListKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.ListKeysResponse {
    try await self.inner.listKeys(request: request, options: options)
  }

  /// Gets the metadata for an API key. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_GetKey")
  public func getKey(
    request: GetKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.Key {
    try await self.inner.getKey(request: request, options: options)
  }

  /// Get the key string for an API key.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_GetKeyString")
  public func getKeyString(
    request: GetKeyStringRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    try await self.inner.getKeyString(request: request, options: options)
  }

  /// Patches the modifiable fields of an API key.
  /// The key string of the API key isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UpdateKey")
  public func updateKey(
    request: UpdateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateKey(request: request, options: options)
  }

  /// Patches the modifiable fields of an API key.
  /// The key string of the API key isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UpdateKey")
  public func updateKeyPollingUntilDone(
    request: UpdateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Key>.State in
      return try op._extractStatus(Key.self)
    }
    let rawOp = try await self.updateKey(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an API key. Deleted key can be retrieved within 30 days of
  /// deletion. Afterward, key will be purged from the project.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_DeleteKey")
  public func deleteKey(
    request: DeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteKey(request: request, options: options)
  }

  /// Deletes an API key. Deleted key can be retrieved within 30 days of
  /// deletion. Afterward, key will be purged from the project.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_DeleteKey")
  public func deleteKeyPollingUntilDone(
    request: DeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Key>.State in
      return try op._extractStatus(Key.self)
    }
    let rawOp = try await self.deleteKey(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeletes an API key which was deleted within 30 days.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UndeleteKey")
  public func undeleteKey(
    request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeleteKey(request: request, options: options)
  }

  /// Undeletes an API key which was deleted within 30 days.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_UndeleteKey")
  public func undeleteKeyPollingUntilDone(
    request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Key>.State in
      return try op._extractStatus(Key.self)
    }
    let rawOp = try await self.undeleteKey(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Find the parent project and resource name of the API
  /// key that matches the key string in the request. If the API key has been
  /// purged, resource name will not be set.
  /// The service account must have the `apikeys.keys.lookup` permission
  /// on the parent project.
  ///
  /// @Snippet(path: "ApiKeys_LookupKey")
  public func lookupKey(
    request: LookupKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse {
    try await self.inner.lookupKey(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiKeys_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiKeysClient`.
  ///
  /// To mock `ApiKeysClient` change your functions to receive
  /// `some ApiKeysProtocol` or `any ApiKeysProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiKeysProtocol: Sendable {
    /// See `ApiKeysClient.createKey`.
    func createKey(
      request: CreateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.createKey`.
    func createKeyPollingUntilDone(
      request: CreateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Key>

    /// See `ApiKeysClient.listKeys`.
    func listKeys(
      request: ListKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.ListKeysResponse

    /// See `ApiKeysClient.getKey`.
    func getKey(
      request: GetKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.Key

    /// See `ApiKeysClient.getKeyString`.
    func getKeyString(
      request: GetKeyStringRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse

    /// See `ApiKeysClient.updateKey`.
    func updateKey(
      request: UpdateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.updateKey`.
    func updateKeyPollingUntilDone(
      request: UpdateKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Key>

    /// See `ApiKeysClient.deleteKey`.
    func deleteKey(
      request: DeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.deleteKey`.
    func deleteKeyPollingUntilDone(
      request: DeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Key>

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKey(
      request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiKeysClient.undeleteKey`.
    func undeleteKeyPollingUntilDone(
      request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Key>

    /// See `ApiKeysClient.lookupKey`.
    func lookupKey(
      request: LookupKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse
  }
}

// Default implementations
extension Clients.ApiKeysProtocol {
  public func createKey(request: CreateKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createKey(request: request, options: .init())
  }

  public func createKey(
    request: CreateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createKeyPollingUntilDone(request: CreateKeyRequest) async throws -> any GoogleGax
    .PollableOperation<Key>
  {
    try await self.createKeyPollingUntilDone(request: request, options: .init())
  }

  public func createKeyPollingUntilDone(
    request: CreateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createKeyPollingUntilDone(
    parent: Swift.String,
    key: Key?,
    keyId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let request = CreateKeyRequest().with {
      $0.parent = parent
      $0.key = key
      $0.keyId = keyId
    }
    return try await self.createKeyPollingUntilDone(request: request)
  }

  public func listKeys(request: ListKeysRequest) async throws -> GoogleApiApiKeysV1.ListKeysResponse
  {
    try await self.listKeys(request: request, options: .init())
  }

  public func listKeys(
    request: ListKeysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.ListKeysResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listKeysByItems(
    request: ListKeysRequest
  ) -> any AsyncSequence<Key, Swift.Error> & Sendable {
    self.listKeysByItems(request: request, options: .init())
  }

  /// Lists the API keys owned by a project. The key string of the API key
  /// isn't included in the response.
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  ///
  /// @Snippet(path: "ApiKeys_ListKeys")
  public func listKeysByItems(
    request: ListKeysRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Key, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleApiApiKeysV1.ListKeysResponse in
      var request = request
      request.pageToken = token
      return try await self.listKeys(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listKeysByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Key, Swift.Error> & Sendable {
    let request = ListKeysRequest().with {
      $0.parent = parent
    }
    return self.listKeysByItems(request: request)
  }

  public func getKey(request: GetKeyRequest) async throws -> GoogleApiApiKeysV1.Key {
    try await self.getKey(request: request, options: .init())
  }

  public func getKey(
    request: GetKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.Key {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getKey(
    name: Swift.String,
  ) async throws -> GoogleApiApiKeysV1.Key {
    let request = GetKeyRequest().with {
      $0.name = name
    }
    return try await self.getKey(request: request)
  }

  public func getKeyString(request: GetKeyStringRequest) async throws
    -> GoogleApiApiKeysV1.GetKeyStringResponse
  {
    try await self.getKeyString(request: request, options: .init())
  }

  public func getKeyString(
    request: GetKeyStringRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getKeyString(
    name: Swift.String,
  ) async throws -> GoogleApiApiKeysV1.GetKeyStringResponse {
    let request = GetKeyStringRequest().with {
      $0.name = name
    }
    return try await self.getKeyString(request: request)
  }

  public func updateKey(request: UpdateKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateKey(request: request, options: .init())
  }

  public func updateKey(
    request: UpdateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateKeyPollingUntilDone(request: UpdateKeyRequest) async throws -> any GoogleGax
    .PollableOperation<Key>
  {
    try await self.updateKeyPollingUntilDone(request: request, options: .init())
  }

  public func updateKeyPollingUntilDone(
    request: UpdateKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateKeyPollingUntilDone(
    key: Key?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let request = UpdateKeyRequest().with {
      $0.key = key
      $0.updateMask = updateMask
    }
    return try await self.updateKeyPollingUntilDone(request: request)
  }

  public func deleteKey(request: DeleteKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteKey(request: request, options: .init())
  }

  public func deleteKey(
    request: DeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteKeyPollingUntilDone(request: DeleteKeyRequest) async throws -> any GoogleGax
    .PollableOperation<Key>
  {
    try await self.deleteKeyPollingUntilDone(request: request, options: .init())
  }

  public func deleteKeyPollingUntilDone(
    request: DeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteKeyPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let request = DeleteKeyRequest().with {
      $0.name = name
    }
    return try await self.deleteKeyPollingUntilDone(request: request)
  }

  public func undeleteKey(request: UndeleteKeyRequest) async throws -> GoogleLongRunning.Operation {
    try await self.undeleteKey(request: request, options: .init())
  }

  public func undeleteKey(
    request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func undeleteKeyPollingUntilDone(request: UndeleteKeyRequest) async throws -> any GoogleGax
    .PollableOperation<Key>
  {
    try await self.undeleteKeyPollingUntilDone(request: request, options: .init())
  }

  public func undeleteKeyPollingUntilDone(
    request: UndeleteKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Key> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Key>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func lookupKey(request: LookupKeyRequest) async throws
    -> GoogleApiApiKeysV1.LookupKeyResponse
  {
    try await self.lookupKey(request: request, options: .init())
  }

  public func lookupKey(
    request: LookupKeyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiApiKeysV1.LookupKeyResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
