// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A restriction for a specific service and optionally one or multiple
/// specific methods. Both fields are case insensitive.
public struct ApiTarget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The service for this restriction. It should be the canonical
  /// service name, for example: `translate.googleapis.com`.
  /// You can use [`gcloud services list`](/sdk/gcloud/reference/services/list)
  /// to get a list of services that are enabled in the project.
  public var service: Swift.String = Swift.String()

  /// Optional. List of one or more methods that can be called.
  /// If empty, all methods for the service are allowed. A wildcard
  /// (*) can be used as the last symbol.
  /// Valid examples:
  ///   `google.cloud.translate.v2.TranslateService.GetSupportedLanguage`
  ///   `TranslateText`
  ///   `Get*`
  ///   `translate.googleapis.com.Get*`
  public var methods: [Swift.String] = []

  /// Initialize a new instance of `ApiTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApiTarget().with { $0.service = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.apikeys.v2.ApiTarget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
