// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The representation of a key managed by the API Keys API.
public struct Key: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the key.
  /// The `name` has the form:
  /// `projects/<PROJECT_NUMBER>/locations/global/keys/<KEY_ID>`.
  /// For example:
  /// `projects/123456867718/locations/global/keys/b7ff1f9f-8275-410a-94dd-3855ee9b5dd2`
  ///
  /// NOTE: Key is a global resource; hence the only supported value for
  /// location is `global`.
  public var name: Swift.String = Swift.String()

  /// Output only. Unique id in UUID4 format.
  public var uid: Swift.String = Swift.String()

  /// Human-readable display name of this key that you can modify.
  /// The maximum length is 63 characters.
  public var displayName: Swift.String = Swift.String()

  /// Output only. An encrypted and signed value held by this key.
  /// This field can be accessed only through the `GetKeyString` method.
  public var keyString: Swift.String = Swift.String()

  /// Output only. A timestamp identifying the time this key was originally
  /// created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. A timestamp identifying the time this key was last
  /// updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. A timestamp when this key was deleted. If the resource is not
  /// deleted, this must be empty.
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Annotations is an unstructured key-value map stored with a policy that
  /// may be set by external tools to store and retrieve arbitrary metadata.
  /// They are not queryable and should be preserved when modifying objects.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Key restrictions.
  public var restrictions: Restrictions? = nil

  /// Output only. A checksum computed by the server based on the current value
  /// of the Key resource. This may be sent on update and delete requests to
  /// ensure the client has an up-to-date value before proceeding. See
  /// https://google.aip.dev/154.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Key`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Key().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let keyString = CodingKeys(stringValue: "keyString")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let restrictions = CodingKeys(stringValue: "restrictions")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "displayName",
      "keyString",
      "createTime",
      "updateTime",
      "deleteTime",
      "annotations",
      "restrictions",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .keyString) {
      self.keyString = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.restrictions = try container.decodeIfPresent(Restrictions.self, forKey: .restrictions)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.keyString, forKey: .keyString)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.restrictions, forKey: .restrictions)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.apikeys.v2.Key"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
