// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes the restrictions on the key.
public struct Restrictions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A restriction for a specific service and optionally one or
  /// more specific methods. Requests are allowed if they
  /// match any of these restrictions. If no restrictions are
  /// specified, all targets are allowed.
  public var apiTargets: [ApiTarget] = []

  /// The websites, IP addresses, Android apps, or iOS apps (the clients) that
  /// are allowed to use the key. You can specify only one type of client
  /// restrictions per key.
  public var clientRestrictions: OneOf_ClientRestrictions? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Restrictions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Restrictions().with { $0.browserKeyRestrictions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let browserKeyRestrictions = CodingKeys(stringValue: "browserKeyRestrictions")
    static let serverKeyRestrictions = CodingKeys(stringValue: "serverKeyRestrictions")
    static let androidKeyRestrictions = CodingKeys(stringValue: "androidKeyRestrictions")
    static let iosKeyRestrictions = CodingKeys(stringValue: "iosKeyRestrictions")
    static let apiTargets = CodingKeys(stringValue: "apiTargets")

    static let _knownKeys: Set<Swift.String> = [
      "browserKeyRestrictions",
      "serverKeyRestrictions",
      "androidKeyRestrictions",
      "iosKeyRestrictions",
      "apiTargets",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([ApiTarget].self, forKey: .apiTargets) {
      self.apiTargets = value
    }

    var clientRestrictions: OneOf_ClientRestrictions? = nil
    let clientRestrictionsCheckAndSet = {
      if clientRestrictions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clientRestrictions'"))
      }
      clientRestrictions = $0
    }
    if let browserKeyRestrictions = try container.decodeIfPresent(
      BrowserKeyRestrictions?.self, forKey: .browserKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.browserKeyRestrictions(browserKeyRestrictions))
    }
    if let serverKeyRestrictions = try container.decodeIfPresent(
      ServerKeyRestrictions?.self, forKey: .serverKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.serverKeyRestrictions(serverKeyRestrictions))
    }
    if let androidKeyRestrictions = try container.decodeIfPresent(
      AndroidKeyRestrictions?.self, forKey: .androidKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.androidKeyRestrictions(androidKeyRestrictions))
    }
    if let iosKeyRestrictions = try container.decodeIfPresent(
      IosKeyRestrictions?.self, forKey: .iosKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.iosKeyRestrictions(iosKeyRestrictions))
    }
    self.clientRestrictions = clientRestrictions
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.apiTargets, forKey: .apiTargets)

    if let choice = self.clientRestrictions {
      switch choice {
      case .browserKeyRestrictions(let value):
        try container.encode(value, forKey: .browserKeyRestrictions)
      case .serverKeyRestrictions(let value):
        try container.encode(value, forKey: .serverKeyRestrictions)
      case .androidKeyRestrictions(let value):
        try container.encode(value, forKey: .androidKeyRestrictions)
      case .iosKeyRestrictions(let value):
        try container.encode(value, forKey: .iosKeyRestrictions)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The websites, IP addresses, Android apps, or iOS apps (the clients) that
  /// are allowed to use the key. You can specify only one type of client
  /// restrictions per key.
  public enum OneOf_ClientRestrictions: Codable, Equatable, Sendable {
    /// The HTTP referrers (websites) that are allowed to use the key.
    indirect case browserKeyRestrictions(BrowserKeyRestrictions?)
    /// The IP addresses of callers that are allowed to use the key.
    indirect case serverKeyRestrictions(ServerKeyRestrictions?)
    /// The Android apps that are allowed to use the key.
    indirect case androidKeyRestrictions(AndroidKeyRestrictions?)
    /// The iOS apps that are allowed to use the key.
    indirect case iosKeyRestrictions(IosKeyRestrictions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.apikeys.v2.Restrictions"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
