// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes the restrictions on the key.
public struct Restrictions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A restriction for a specific service and optionally one or
  /// more specific methods. Requests are allowed if they
  /// match any of these restrictions. If no restrictions are
  /// specified, all targets are allowed.
  public var apiTargets: [ApiTarget] = []

  /// The websites, IP addresses, Android apps, or iOS apps (the clients) that
  /// are allowed to use the key. You can specify only one type of client
  /// restrictions per key.
  public var clientRestrictions: OneOf_ClientRestrictions? = nil

  /// Initialize a new instance of `Restrictions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Restrictions().with { $0.browserKeyRestrictions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case browserKeyRestrictions = "browserKeyRestrictions"
    case serverKeyRestrictions = "serverKeyRestrictions"
    case androidKeyRestrictions = "androidKeyRestrictions"
    case iosKeyRestrictions = "iosKeyRestrictions"
    case apiTargets = "apiTargets"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.apiTargets = try container.decode([ApiTarget].self, forKey: .apiTargets)

    var clientRestrictions: OneOf_ClientRestrictions? = nil
    let clientRestrictionsCheckAndSet = {
      if clientRestrictions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clientRestrictions'"))
      }
      clientRestrictions = $0
    }
    if let browserKeyRestrictions = try container.decodeIfPresent(
      BrowserKeyRestrictions?.self, forKey: .browserKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.browserKeyRestrictions(browserKeyRestrictions))
    }
    if let serverKeyRestrictions = try container.decodeIfPresent(
      ServerKeyRestrictions?.self, forKey: .serverKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.serverKeyRestrictions(serverKeyRestrictions))
    }
    if let androidKeyRestrictions = try container.decodeIfPresent(
      AndroidKeyRestrictions?.self, forKey: .androidKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.androidKeyRestrictions(androidKeyRestrictions))
    }
    if let iosKeyRestrictions = try container.decodeIfPresent(
      IosKeyRestrictions?.self, forKey: .iosKeyRestrictions)
    {
      try clientRestrictionsCheckAndSet(.iosKeyRestrictions(iosKeyRestrictions))
    }
    self.clientRestrictions = clientRestrictions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.apiTargets, forKey: .apiTargets)

    if let choice = self.clientRestrictions {
      switch choice {
      case .browserKeyRestrictions(let value):
        try container.encode(value, forKey: .browserKeyRestrictions)
      case .serverKeyRestrictions(let value):
        try container.encode(value, forKey: .serverKeyRestrictions)
      case .androidKeyRestrictions(let value):
        try container.encode(value, forKey: .androidKeyRestrictions)
      case .iosKeyRestrictions(let value):
        try container.encode(value, forKey: .iosKeyRestrictions)
      }
    }
  }

  /// The websites, IP addresses, Android apps, or iOS apps (the clients) that
  /// are allowed to use the key. You can specify only one type of client
  /// restrictions per key.
  public enum OneOf_ClientRestrictions: Codable, Equatable, Sendable {
    /// The HTTP referrers (websites) that are allowed to use the key.
    indirect case browserKeyRestrictions(BrowserKeyRestrictions?)
    /// The IP addresses of callers that are allowed to use the key.
    indirect case serverKeyRestrictions(ServerKeyRestrictions?)
    /// The Android apps that are allowed to use the key.
    indirect case androidKeyRestrictions(AndroidKeyRestrictions?)
    /// The iOS apps that are allowed to use the key.
    indirect case iosKeyRestrictions(IosKeyRestrictions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.apikeys.v2.Restrictions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
